### ISSUE TITLE
Nuget package ?

### ISSUE THREAD

**Issue by YBAZAN** [syncfusion/Uno.SfChart#1]
I wonder if there is a reason to not publish it as Nuget package ? It would be so useful instead of getting the code source and reference it in our projects.

**Comment by karthikeyanvis** [comment]
Currently UNO project dependencies are not stable and also changing the structure of Nuget Package. Hence, once confirmed the UNO package is stable, we can publish the Nuget packages. We will let you know once it gets rolled out, please wait until then.

**Comment by karthikeyanvis** [comment]
We are the Uno SfChart of experimental development. We are still developing and improving control on the basis of the customer's request. For our main release, we'll include the Nuget version.
