### ISSUE TITLE
How is this code licensed?

### ISSUE THREAD

**Issue by mrlacey** [syncfusion/Uno.SfChart#11]
Without knowing how this code is licensed I can't use it or even risk looking at the code to see if it is appropriate to consider using it.
Please can you add a license file, or indicate in some other way how the code in this repository is licensed?

**Comment by SyncfusionKarthikeyan** [comment]
Currently we have published the beta version Syncfusion Uno chart control and it’s license free control for beta version.

**Comment by mrlacey** [comment]
> it’s license free control for beta version.

**What does this mean?**

Does it mean anyone is free to use it in any way while the beta version is still available?
What about continuing to use the code from this beta version once you have a release version?
How is this control expected to be licensed once the beta version is no longer available or the beta period ends?
If I'm happy with the quality of the beta version and ship an app that uses it, what is the licensing situation once you go beyond the beta version?
Do I have permission to ship an app that uses the current beta version? Or is it only available for evaluation?
Will this repo be removed when the beta period ends? And if so, what about any forks or copies of the code?
As the copyright holder of the code in this repository, what am I allowed to do with this code? Anything?  Nothing? Some things?

Separately, I've been told by another member of SyncFusion staff that this repository is licensed under the "Syncfusion Community License Program" so which is it?


Why not add a license file to this repository to clear up the potential for confusion?

**Comment by SyncfusionKarthikeyan** [comment]
@mrlacey Added license file. Please refer [here](https://github.com/syncfusion/Uno.SfChart/blob/master/LICENSE.MD)
