### ISSUE TITLE
Is there any new version coming along?

### ISSUE THREAD

**Issue by ryan-seifi** [syncfusion/Uno.SfChart#5]
Hi, I've been using this library for a while and I noticed some issues regarding performance and some other issues like not being able to use xaml designer.

I have noticed that this library is not under active development and it was more like a one time go.

Do you have any plans to develop this library further?

**Comment by karthikeyanvis** [comment]
We are the Uno SfChart of experimental development. We are still developing and improving control on the basic of the customer's request.
