### ISSUE TITLE
Stacked Series contains spaces when generated

### ISSUE THREAD

**Issue by vkudelas** [syncfusion/Uno.SfChart#7]
Used C# code to generate stacked series. 
IsIndexed option of category axis is false.
Generated series contains spaces:

![Screenshot 2021-04-19 223217](https://user-images.githubusercontent.com/82843490/115299811-934a0980-a15f-11eb-9bba-6efbbcade607.png)

**Comment by karthikeyanvis** [comment]
Issue has been resolved.
